### PR TITLE
fix(styled-components): fix SSR and error styles

### LINKED ISSUE #167: No "working" styled-components example
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

[official styled-components example](https://github.com/remix-run/examples/tree/main/styled-components) 

### Expected Behavior

That it will render both on first load as well as consecutive loads without err.

### Actual Behavior

Exhibits [the hydration issues mentioned here](https://github.com/styled-components/styled-components/issues/3660). 
However, in our experience, the styles match fine on FIRST load. Only on page refresh do them become broken. Even with JS disabled this issue persists, which leads me to believe the issue is strictly an SSR one for the moment.

It does not appear that it will work with any SSR without the aid of [babel-plugin-styled-components](https://github.com/styled-components/babel-plugin-styled-components) which itself is not supported in Remix since it doesn't seem we have access to plugins or modifying esbuild config. 
 
As a comparison, Next.js allows you to control webpack option values from a configuration file (next.config.js) so they can implement the needed plugins. A member of the development team says in a PR comment that this is because exposing the configuration values would lock in the compiler's choices and also risk breaking the application.

This limitation seems to be leading some remix users to [implement workarounds](https://mortenbarklund.com/blog/styled-components-remix) using a [custom module to override esbuild](https://github.com/aiji42/remix-esbuild-override).

Then there are a [number of other mentions](https://github.com/remix-run/remix/discussions/5244#discussioncomment-4832036) out there of [similar issues](https://github.com/remix-run/remix/discussions/5244) that link around and I'm not even quite sure if its relates to the same hydration issue or not, but certainly sounds like it would affect the existing example.

There are even [posts about how to do this with NextJS that say there are no issues](https://dev.to/britotiagos/how-add-style-components-to-nextjs-and-start-using-it-4kdf).... but that seems odd when the example doesnt seem to need `babel-plugin-styled-components`.

@kentcdodds [mentions a possible fix here using patch-package](https://github.com/styled-components/styled-components/issues/3660#issuecomment-1330947832), however then @jmurzy [mentions that the needed code is stripped out](https://github.com/styled-components/styled-components/issues/3660#issuecomment-1416185601), rendering that possible fix incomplete.

For added injury, we also need to get Material-UI v4 working, which seems to have exactly the same issue. First load, all the style names match up, on reload, none match. This is also with JS disabled, so it appears again to be an SSR only issue.

# Conclusion
None of the methods above seem to work for us, and we're currently not clear if its because we use **pnpm** or that it's a **monorepo**, or that we also implement our own **custom react ui lib** that also uses `babel-plugin-styled-components` but in any case, none seem to work. 

We're VERY much wanting to migrate all our sites to Remix but need to slowly migrate away from styled-components, and not cold-turkey cut it off. So we need a migration path for styled-components with Remix.

### PR DESCRIPTION
**Pull request by markdalgleish**
Fixes #167

This fixes some longstanding issues with hydration errors and missing styles when navigating to/from error routes. I've also updated this example to use React 18 to show that it now works with stricter hydration.

Related issue: https://github.com/remix-run/remix/issues/1136

### CODE REVIEW

File: styled-components/app/routes/__boundary/$.tsx [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+  throw new Response(null, {
+    status: 404,
+    statusText: "Not Found",
+  });
+};
+
+export default function NotFound() {
+  // This is needed to tell Remix it isn't a resource route
+  return <></>;
+}
```
Comment (MichaelDeBoey) [inline styled-components/app/routes/__boundary/$.tsx:12]:
```suggestion
// This is needed to tell Remix it isn't a resource route
export default () => null;
```

File: styled-components/app/entry.client.tsx
Comment (MichaelDeBoey) [inline styled-components/app/entry.client.tsx:1]: I guess we can just remove this file now that it's in line with the default one?

**Review by MichaelDeBoey — CHANGES_REQUESTED** [review]
